CREATE DATABASE Locadora_Manha;
USE Locadora_Manha;

CREATE TABLE Empresa (
	IdEmpresa INT PRIMARY KEY IDENTITY NOT NULL,
	Nome VARCHAR (200)
);
CREATE TABLE Cliente (
	IdCliente INT PRIMARY KEY IDENTITY NOT NULL,
	Nome VARCHAR (200),
	CPF VARCHAR (100)
);
CREATE TABLE Veiculo (
	IdVeiculo INT PRIMARY KEY IDENTITY NOT NULL,
	Placa INT ,
	IdEmpresa INT FOREIGN KEY REFERENCES Empresa (IdEmpresa),
	IdModelo INT FOREIGN KEY REFERENCES Modelo (IdModelo)
);
CREATE TABLE Aluguem (
	IdAluguem INT PRIMARY KEY IDENTITY NOT NULL,
	DataInicio VARCHAR (200),
	DataFinal VARCHAR (200),
	IdVeiculo INT FOREIGN KEY REFERENCES Veiculo (IdVeiculo),
	IdCliente INT FOREIGN KEY REFERENCES Cliente (IdCliente)
);
CREATE TABLE Marca (
	IdMarca INT PRIMARY KEY IDENTITY NOT NULL,
	Nome VARCHAR (200)
);
CREATE TABLE Modelo (
	IdModelo INT PRIMARY KEY IDENTITY NOT NULL,
	Nome VARCHAR (200),
	IdMarca INT FOREIGN KEY REFERENCES Marca (IdMarca)
);
 SELECT * FROM Veiculo;
 SELECT * FROM Empresa;
  SELECT * FROM Cliente;
 SELECT * FROM Modelo;
  SELECT * FROM Marca;

  
ALTER TABLE Veiculo
ADD Placa INT;

ALTER TABLE Veiculo
DROP COLUMN Placa;
